configuration:
  sinks: [0, 1, 2]
  sources:
    0: {upstream_conv: 0}
    1: {upstream_conv: 1}
    2: {upstream_conv: 2}
  conveyors:
    0:
      length: 10
      upstream: {type: 'conveyor', idx: 3, pos: 0}
    1:
      length: 10
      upstream: {type: 'conveyor', idx: 3, pos: 20}
    2:
      length: 10
      upstream: {type: 'conveyor', idx: 3, pos: 40}
    3:
      length: 60
      upstream: {type: 'conveyor', idx: 7, pos: 0}
    4:
      length: 10
      upstream: {type: 'conveyor', idx: 8, pos: 50}
    5:
      length: 10
      upstream: {type: 'conveyor', idx: 8, pos: 30}
    6:
      length: 10
      upstream: {type: 'conveyor', idx: 8, pos: 10}
    7:
      length: 10
      upstream: {type: 'conveyor', idx: 8, pos: 0}
    8:
      length: 60
      upstream: {type: 'conveyor', idx: 9, pos: 0}
    9:
      length: 10
      upstream: {type: 'sink', idx: 0}
    10:
      length: 10
      upstream: {type: 'sink', idx: 1}
    11:
      length: 10
      upstream: {type: 'sink', idx: 2}
  diverters:
    0:
      conveyor: 3
      pos: 10
      upstream_conv: 4
    1:
      conveyor: 3
      pos: 30
      upstream_conv: 5
    2:
      conveyor: 3
      pos: 50
      upstream_conv: 6
    3:
      conveyor: 8
      pos: 20
      upstream_conv: 11
    4:
      conveyor: 8
      pos: 40
      upstream_conv: 10

settings:
  bags_distr:
    sequence:
      # - {pkg_number: 1000, delta: 10} 
      # - {bags_number: 2000, delta: 10}
      - {bags_number: 200, delta: 50, sources: [2], sinks: [2]}
      - {bags_number: 200, delta: 50, sources: [1, 2], sinks: [1, 2]}
      - {bags_number: 200, delta: 50}
      - {bags_number: 200, delta: 50, sources: [2], sinks: [2]}
      - {bags_number: 200, delta: 50, sources: [1, 2], sinks: [1, 2]}
      - {bags_number: 200, delta: 50}
      - {bags_number: 200, delta: 50, sources: [2], sinks: [2]}
      - {bags_number: 200, delta: 50, sources: [1, 2], sinks: [1, 2]}
      - {bags_number: 200, delta: 50}
      # - {bags_number: 200, delta: 20, sources: [2], sinks: [2]}
      # - {bags_number: 200, delta: 20, sources: [1, 2], sinks: [1, 2]}
      # - {bags_number: 200, delta: 20}

  conveyor_env:
    speed: 1
    energy_consumption: 1
  conveyor:
    stop_delay: 40
    slowdown_delay: 1
  router:
    simple_q:
      energy_reward_weight: 0.4 # * 0.0002
      learning_rate: 0.5
    dqn: &dqn
      energy_reward_weight: 1
      optimizer: 'rmsprop'
      scope: 'conveyor_test_ng'
      activation: 'relu'
      layers: [64, 64]
      additional_inputs:
        - tag: 'amatrix'
      batch_size: 1
      mem_capacity: 1
    dqn_oneout:
      <<: *dqn
    dqn_emb:
      <<: *dqn
      energy_reward_weight: 0.5
      additional_inputs: []
      embedding:
        alg: 'lap'
        dim: 10
