network:
  - {u: 0, v: 1, latency: 14, bandwidth: 256}
  - {u: 0, v: 2, latency: 15, bandwidth: 256}
  - {u: 1, v: 2, latency: 10, bandwidth: 256}
  - {u: 1, v: 3, latency: 13, bandwidth: 256}
  - {u: 1, v: 4, latency: 20, bandwidth: 256}
  - {u: 2, v: 3, latency: 20, bandwidth: 256}
  - {u: 2, v: 4, latency: 13, bandwidth: 256}
  - {u: 3, v: 4, latency: 10, bandwidth: 256}
  - {u: 3, v: 5, latency: 14, bandwidth: 256}
  - {u: 4, v: 5, latency: 15, bandwidth: 256}
settings:
  pkg_distr:
    sequence:
      - {pkg_number: 5000, delta: 2}
      - {pkg_number: 10000, delta: 1}
  synchronizer:
    period: 20
    delta: 5
  logging:
    delta: 10
  router_env:
    pkg_process_delay: 3
  router:
    learning_rate: 0.2
