network:
  - {u: 0, v: 1, latency: 10, bandwidth: 1024}
  - {u: 0, v: 2, latency: 10, bandwidth: 1024}
  - {u: 1, v: 6, latency: 10, bandwidth: 1024}
  - {u: 2, v: 6, latency: 10, bandwidth: 1024}
  - {u: 1, v: 8, latency: 10, bandwidth: 1024}
  - {u: 8, v: 9, latency: 10, bandwidth: 1024}
  - {u: 6, v: 7, latency: 10, bandwidth: 1024}
  - {u: 3, v: 4, latency: 10, bandwidth: 1024}
  - {u: 4, v: 5, latency: 10, bandwidth: 1024}
  - {u: 3, v: 7, latency: 10, bandwidth: 1024}
  - {u: 5, v: 7, latency: 10, bandwidth: 1024}
  - {u: 5, v: 9, latency: 10, bandwidth: 1024}

settings:
  pkg_distr:
    seed: 42
    sequence:
      - {pkg_number: 5000, delta: 10} 
      - {action: 'break_link', pause: 10, u: 0, v: 1}
      - {pkg_number: 5000, delta: 10} 
      - {action: 'restore_link', pause: 10, u: 0, v: 1}
      - {action: 'break_link', pause: 10, u: 0, v: 2}
      - {pkg_number: 5000, delta: 10} 
      - {action: 'restore_link', pause: 10, u: 0, v: 2}
      - {action: 'break_link', pause: 10, u: 1, v: 6}
      - {pkg_number: 5000, delta: 10} 
      - {action: 'restore_link', pause: 10, u: 1, v: 6}
      - {action: 'break_link', pause: 10, u: 2, v: 6}
      - {pkg_number: 5000, delta: 10} 
      - {action: 'restore_link', pause: 10, u: 2, v: 6}
      - {action: 'break_link', pause: 10, u: 1, v: 8}
      - {pkg_number: 5000, delta: 10} 
      - {action: 'restore_link', pause: 10, u: 1, v: 8}
      - {action: 'break_link', pause: 10, u: 8, v: 9}
      - {pkg_number: 5000, delta: 10} 
      - {action: 'restore_link', pause: 10, u: 8, v: 9}
      - {action: 'break_link', pause: 10, u: 6, v: 7}
      - {pkg_number: 5000, delta: 10} 
      - {action: 'restore_link', pause: 10, u: 6, v: 7}
      - {action: 'break_link', pause: 10, u: 3, v: 4} 
      - {pkg_number: 5000, delta: 10} 
      - {action: 'restore_link', pause: 10, u: 3, v: 4}
      - {action: 'break_link', pause: 10, u: 4, v: 5}
      - {pkg_number: 5000, delta: 10} 
      - {action: 'restore_link', pause: 10, u: 4, v: 5}
      - {action: 'break_link', pause: 10, u: 3, v: 7}
      - {pkg_number: 5000, delta: 10} 
      - {action: 'restore_link', pause: 10, u: 3, v: 7}
      - {action: 'break_link', pause: 10, u: 5, v: 7}
      - {pkg_number: 5000, delta: 10} 
      - {action: 'restore_link', pause: 10, u: 5, v: 7}
      - {action: 'break_link', pause: 10, u: 5, v: 9}
      - {pkg_number: 5000, delta: 10} 
      # - {pkg_number: 500, delta: 20, sources: [0, 1, 2, 8], dests: [3, 4, 5, 9]}
  synchronizer:
    period: 100
    delta: 10
  logging:
    delta: 200
  router_env:
    pkg_process_delay: 5
  router:
    learning_rate: 0.2
    model_file: null
    batch_size: 1
    mem_capacity: 1
    prioritized_xp: False
 
