network:
  - {u: 0, v: 1, latency: 10, bandwidth: 1024}
  - {u: 0, v: 2, latency: 10, bandwidth: 1024}
  - {u: 1, v: 6, latency: 10, bandwidth: 1024}
  - {u: 2, v: 6, latency: 10, bandwidth: 1024}
  - {u: 1, v: 8, latency: 10, bandwidth: 1024}
  - {u: 8, v: 9, latency: 10, bandwidth: 1024}
  - {u: 6, v: 7, latency: 10, bandwidth: 1024}
  - {u: 3, v: 4, latency: 10, bandwidth: 1024}
  - {u: 4, v: 5, latency: 10, bandwidth: 1024}
  - {u: 3, v: 7, latency: 10, bandwidth: 1024}
  - {u: 5, v: 7, latency: 10, bandwidth: 1024}
  - {u: 5, v: 9, latency: 10, bandwidth: 1024}

settings:
  pkg_distr:
    sequence:
      # - {pkg_number: 1000, delta: 10} 
      - {pkg_number: 100, delta: 10}
      - {pkg_number: 500, delta: 10, sources: [0, 1, 2, 6], dests: [3, 4, 5, 7]}
      - {action: 'break_link', pause: 20, u: 6, v: 7}
      - {pkg_number: 500, delta: 10, sources: [0, 1, 2, 6], dests: [3, 4, 5, 7]}
      - {action: 'break_link', pause: 20, u: 0, v: 1}
      - {pkg_number: 500, delta: 10, sources: [0, 1, 2, 6], dests: [3, 4, 5, 7]}
      - {action: 'break_link', pause: 20, u: 4, v: 5}
      - {pkg_number: 500, delta: 10, sources: [0, 1, 2, 6], dests: [3, 4, 5, 7]}
      - {action: 'restore_link', pause: 20, u: 6, v: 7}
      - {pkg_number: 500, delta: 10, sources: [0, 1, 2, 6], dests: [3, 4, 5, 7]}
      - {action: 'restore_link', pause: 20, u: 0, v: 1}
      - {pkg_number: 500, delta: 10, sources: [0, 1, 2, 6], dests: [3, 4, 5, 7]}
      - {action: 'restore_link', pause: 20, u: 4, v: 5}
      - {pkg_number: 500, delta: 10, sources: [0, 1, 2, 6], dests: [3, 4, 5, 7]}
  router_env:    
    pkg_process_delay: 5
  router:
    simple_q:
      learning_rate: 0.5
    pred_q:
      learning_rate: 1.0
      beta: 0.7
      gamma: 0.9
    dqn: &dqn
      optimizer: 'rmsprop'
      activation: 'relu'
      layers: [64, 64]
      additional_inputs:
        - tag: 'amatrix'
      batch_size: 1
      mem_capacity: 1
    dqn_oneout:
      <<: *dqn
    dqn_emb:
      <<: *dqn
      additional_inputs: []
      embedding:
        alg: 'lap'
        dim: 8
