settings:
  bags_distr:
    sequence:
      - {bags_number: 200, delta: 20, sinks: [0, 1, 2, 3, 4, 5, 6]}
      - {bags_number: 200, delta: 20}
      - {bags_number: 200, delta: 20, sinks: [7, 8, 9, 10, 11, 12]} 
      - {bags_number: 200, delta: 20}
      - {bags_number: 200, delta: 20, sinks: [0, 1, 2, 3, 4, 5, 6]} 
      - {bags_number: 200, delta: 20}
      - {bags_number: 200, delta: 20, sinks: [7, 8, 9, 10, 11, 12]} 
  conveyor_env:
    speed: 1
    energy_consumption: 1
  conveyor:
    stop_delay: 40
    slowdown_delay: 1
  router:
    simple_q:
      energy_reward_weight: 0.4 # * 0.0002
      learning_rate: 0.5
    dqn: &dqn
      energy_reward_weight: 1
      optimizer: 'rmsprop'
      scope: 'conveyor_test_ng'
      activation: 'relu'
      layers: [64, 64]
      additional_inputs:
        - tag: 'amatrix'
      batch_size: 1
      mem_capacity: 1
      softmax_temperature: 3.0 # added by Igor
      probability_smoothing: 0.01 # added by Igor
    dqn_oneout:
      <<: *dqn
    dqn_emb:
      <<: *dqn
      energy_reward_weight: 0.5
      additional_inputs: []
      embedding:
        alg: 'lap'
        dim: 12
